---
title: "Machine Learning with R"
date: '`r format(Sys.time(), "%d %B, %Y")`'
author: John James  jjames@dataScienceSalon.org
output:
  rmdformats::readthedown:
    highlight: kate
bibliography: Machine Learning.BIB
---


```{r knitr_init, echo=FALSE, cache=FALSE, warning=FALSE, message=FALSE}
library(knitr)
library(kfigr)
library(rmdformats)
library(dplyr)
library(ggplot2)
library(statsr)
library(RColorBrewer)

## Global options
options(knitr.table.format = "html")
options(max.print="75", scipen=999, width = 800)
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               fig.height = 4,
               fig.width = 10,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
knitr::opts_knit$set(width=100, figr.prefix = T, figr.link = T)
knitr::knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark=",")
})
```

# Machine Learning with R
```{r child = "s41.Rmd"}
```
```{r child = "s42.Rmd"}
```
```{r child = "s43.Rmd"}
```
```{r child = "s44.Rmd"}
```
