## Introduction 
This section provides a broad introduction to supervised and unsupervised machine learning using Octave, an open-source, scientific programming language [@EatonJohn2017], largely compatible with Matlab [@TheMathworksInc.2016]. Much of the structure, content, and programming problem sets, are drawn from Andrew Ng's Course on Machine Learning [@Nga], delivered on the Coursera platform. For more information on this spectacular course, you are encouraged to visit the Coursera website. A link to the course can be found in the references.

### Learning Objectives
In this section, we will explore, practice, and implement the most effective machine learning techniques used by many practitioners in Silicon Valley,  We will learn not only the theoretical foundations, but also the practical aspects that are needed to quickly and powerfully apply these techniques and algorithms to new problems. Topics include: (i) Supervised learning (linear and logistic regression, machine learning algorithms, support vector machines, kernels, and  neural networks); (ii) Unsupervised learning (clustering, dimensionality reduction, anomaly detection, recommender systems, and deep learning), and (iii) through case studies, we will explore best practices in the application of machine learning to problems in areas such as robotics, bioinformatics, speech recognition, computer vision, medical diagnosis, stock trading, and others. 

### Section Organization
Machine learning problems are primarily categorized as supervised or unsupervised learning. Supervised learning problems are those in which, a hypothesis function is inferred from labeled training data. The task, given the presence of the outcome variable, is to formulate a hypothesis function that comes closest to predicting the outcome. Conversely, the unsupervised learning task is one in which no outcome variables are provided. Rather, the task is to discern patterns and recognize clusters in the data. The first section will focus on supervised learning.  In the second section, we'll tackle supervised learning and finally, we'll explore best practices.  

This section is organized as follows:   

1. Supervised Learning   
1.1. Linear Regression   
1.2. Logistic Regression   
1.3. Neural Networks   
1.4. Support Vector Machines  
  
2. Unsupervised Learning   
2.1. Dimensionality Reduction   
2.2. Anomaly Detection   
2.3. Recommender Systems    
  
3. Best Practices   
3.1. Applying Machine Learning   
3.2. Machine Learning System Design   
3.3. Large Scale Machine Learning   

The theoretical knowledge and practical skills acquired in this section will enable us to start new careers in machine learning, advance existing careers, and tackle interesting real-world problems in machine learning and artificial intelligence.